### ISSUE TITLE
未查询到配置项

### ISSUE THREAD

**Issue by YingLing3** [LambdaYH/zhenxun_plugin_weibo#11]
新版本无法使用，
![image](https://user-images.githubusercontent.com/44056856/226510521-7de511e0-f795-40c8-9858-d49a716f3ae8.png)

在自带配置文件配置了fomat后还是会去真寻配置文件下寻找，且手动在真寻配置文件里加了DEFAULT_FORMAT: 1后重启，插件自动删除此配置
![image](https://user-images.githubusercontent.com/44056856/226510419-0acf03bc-5de3-4e74-87e5-b3daf66c8ddd.png)

**Comment by LambdaYH** [comment]
`FORWARD_MODE`、`DEFAULT_FORMAT`、`COOKIE`这三个都是在真寻的配置文件里配置的

可以让我看看你真寻配置文件下的
zhenxun_plugin_weibo-main: 下面的相关配置吗，我怀疑新版真寻下默认小写了

**Comment by YingLing3** [comment]
> `FORWARD_MODE`、、这三个都是在真寻的配置文件里配置的`DEFAULT_FORMAT``COOKIE`
> 
> 可以让我看看你真寻配置文件下的 zhenxun_plugin_weibo-main： 下面的相关配置吗，我怀疑新版真寻下默认小写了
![image](https://user-images.githubusercontent.com/44056856/226518151-f61de596-f938-47fe-bcfb-2a7402678744.png)

![image](https://user-images.githubusercontent.com/44056856/226518047-6b68e91e-6ede-4d22-85d0-12a67f07d202.png)
只有一个配置生效了其他两个没有生效

**Comment by LambdaYH** [comment]
emmm，我刚刚全新装了个真寻，然后使用了一下插件，没有问题

你可以试试将`data/configs/plugins2config.yaml`中的相关项补齐，可能以前你动了那个文件
```yaml
zhenxun_plugin_weibo-main:
  FORWARD_MODE:
    value: false
    name:
    help: 是否以转发模式推送微博，当配置项为true时将以转发模式推送
    default_value: false
    level_module:
    arg_parser:
  DEFAULT_FORMAT:
    value: 1
    name:
    help: 默认推送格式：0 文本，1 图片
    default_value: 1
    level_module:
    arg_parser:
  COOKIE:
    value:
    name:
    help: 添加cookie后可以获取到更多的微博
    default_value:
    level_module:
    arg_parser:
```
