### ISSUE TITLE
获取到订阅信息后的报错

### ISSUE THREAD

**Issue by 15220526** [LambdaYH/zhenxun_plugin_weibo#5]
请问这是什么问题呢，早上刚刚更新的真寻会不会是更新的问题
![image](https://user-images.githubusercontent.com/106159640/209769811-49534ac3-4781-4e18-9b9a-9aacf5e6276c.png)

**Comment by LambdaYH** [comment]
把本插件代码更新到最新

**Comment by 15220526** [comment]
我直接覆盖了源文件后又出现了这些报错，哪里出问题了吗
![image](https://user-images.githubusercontent.com/106159640/209772149-aadfa4ef-434c-436c-8ccf-4333d77e34c6.png)

**Comment by LambdaYH** [comment]
emm，如果是这问题的话应该老版本也会有，能告知下报错的微博用户ID吗

**Comment by 15220526** [comment]
用户id：5594559637
之前没有注意到有这个报错

**Comment by LambdaYH** [comment]
这个报错是只出现一次还是每次都有？我刚刚试了试似乎蛮正常的。如果是只出现一次的话那可能是网络波动

**Comment by 15220526** [comment]
每次在查询新动态的时候，到这个用户就会报错，然后现在是获取到了用户新微博了，报错还在，但是还是可以正常进行推送提醒

**Comment by LambdaYH** [comment]
确定是这个用户吗，如果可以的话把这部分的日志贴上来吧（带上下文的），因为我测试了这个用户没有报异常。

配置：
```yaml
weibo-test:
  desciption: 测试微博推送
  enable_on_default: false
  format: 0
  users:
  - user_id: '5594559637'
    filter_retweet: false
    filter_words: []
```
图：
![image](https://user-images.githubusercontent.com/13503375/209777952-be8312ae-686e-4066-810a-0bdd2aa4bb1c.png)
